let
    Source = AnalysisServices.Databases("wesc-scsm-02", [TypedMeasureColumns=true]),
    DWASDataBase = Source{[Name="DWASDataBase"]}[Data],
    SystemCenterWorkItemsCube = DWASDataBase{[Id="SystemCenterWorkItemsCube"]}[Data],
    SystemCenterWorkItemsCube1 = SystemCenterWorkItemsCube{[Id="SystemCenterWorkItemsCube"]}[Data],
    #"Added Items" = Cube.Transform(SystemCenterWorkItemsCube1,
        {
            {Cube.AddAndExpandDimensionColumn, "[AssignedToUserDim]", {"[AssignedToUserDim].[City].[City]", "[AssignedToUserDim].[Company].[Company]", "[AssignedToUserDim].[Department].[Department]"}, {"AssignedToUserDim.City", "AssignedToUserDim.Company", "AssignedToUserDim.Department"}},
            {Cube.AddAndExpandDimensionColumn, "[Incident_CreatedDate]", {"[Incident_CreatedDate].[CalendarDate].[CalendarDate]", "[Incident_CreatedDate].[CalendarMonth].[CalendarMonth]", "[Incident_CreatedDate].[DayOfWeek].[DayOfWeek]", "[Incident_CreatedDate].[IsWeekDay].[IsWeekDay]", "[Incident_CreatedDate].[MonthNumber].[MonthNumber]", "[Incident_CreatedDate].[WeekNumberInYear].[WeekNumberInYear]", "[Incident_CreatedDate].[YearNumber].[YearNumber]"}, {"Incident_CreatedDate.CalendarDate", "Incident_CreatedDate.CalendarMonth", "Incident_CreatedDate.DayOfWeek", "Incident_CreatedDate.IsWeekDay", "Incident_CreatedDate.MonthNumber", "Incident_CreatedDate.WeekNumberInYear", "Incident_CreatedDate.YearNumber"}},
            {Cube.AddAndExpandDimensionColumn, "[Incident_ResolvedDate]", {"[Incident_ResolvedDate].[CalendarDate].[CalendarDate]", "[Incident_ResolvedDate].[CalendarMonth].[CalendarMonth]", "[Incident_ResolvedDate].[DayOfWeek].[DayOfWeek]", "[Incident_ResolvedDate].[IsWeekDay].[IsWeekDay]", "[Incident_ResolvedDate].[MonthNumber].[MonthNumber]", "[Incident_ResolvedDate].[WeekNumberInYear].[WeekNumberInYear]", "[Incident_ResolvedDate].[YearNumber].[YearNumber]"}, {"Incident_ResolvedDate.CalendarDate", "Incident_ResolvedDate.CalendarMonth", "Incident_ResolvedDate.DayOfWeek", "Incident_ResolvedDate.IsWeekDay", "Incident_ResolvedDate.MonthNumber", "Incident_ResolvedDate.WeekNumberInYear", "Incident_ResolvedDate.YearNumber"}},
            {Cube.AddAndExpandDimensionColumn, "[IncidentDim_IncidentClassification]", {"[IncidentDim_IncidentClassification].[IncidentClassificationValue].[IncidentClassificationValue]"}, {"IncidentDim_IncidentClassification.IncidentClassificationValue"}},
            {Cube.AddAndExpandDimensionColumn, "[IncidentDim_IncidentResolutionCategory]", {"[IncidentDim_IncidentResolutionCategory].[IncidentResolutionCategoryValue].[IncidentResolutionCategoryValue]"}, {"IncidentDim_IncidentResolutionCategory.IncidentResolutionCategoryValue"}},
            {Cube.AddAndExpandDimensionColumn, "[IncidentDim_IncidentSource]", {"[IncidentDim_IncidentSource].[IncidentSourceValue].[IncidentSourceValue]"}, {"IncidentDim_IncidentSource.IncidentSourceValue"}},
            {Cube.AddAndExpandDimensionColumn, "[IncidentDim_IncidentTierQueues]", {"[IncidentDim_IncidentTierQueues].[IncidentTierQueuesValue].[IncidentTierQueuesValue]"}, {"IncidentDim_IncidentTierQueues.IncidentTierQueuesValue"}},
            {Cube.AddMeasureColumn, "IncidentDimCount", "[Measures].[IncidentDimCount]"},
            {Cube.AddMeasureColumn, "Incidents Active", "[Measures].[Incidents Active]"},
            {Cube.AddMeasureColumn, "Incidents Average Resolution Time (Hours)", "[Measures].[Incidents Average Resolution Time (Hours)]"},
            {Cube.AddMeasureColumn, "Incidents Escalated", "[Measures].[Incidents Escalated]"},
            {Cube.AddMeasureColumn, "Incidents Opened", "[Measures].[Incidents Opened]"},
            {Cube.AddMeasureColumn, "Incidents Resolution Time In Hours Sum", "[Measures].[IncidentDim_IncidentsResolutionTimeInHoursSum]"},
            {Cube.AddMeasureColumn, "Incidents Resolved Count", "[Measures].[IncidentDim_IncidentsResolvedCount]"},
            {Cube.AddAndExpandDimensionColumn, "[AffectedUserDim]", {"[AffectedUserDim].[City].[City]", "[AffectedUserDim].[Company].[Company]", "[AffectedUserDim].[DisplayName].[DisplayName]", "[AffectedUserDim].[Title].[Title]", "[AffectedUserDim].[Zip].[Zip]"}, {"AffectedUserDim.City", "AffectedUserDim.Company", "AffectedUserDim.Display Name (UserDim)", "AffectedUserDim.Title", "AffectedUserDim.Zip"}}
        }),
    #"Filtered Rows1" = Table.SelectRows(#"Added Items", each (Cube.AttributeMemberId([Incident_ResolvedDate.YearNumber]) = "[Incident_ResolvedDate].[YearNumber].&[2015]" meta [DisplayName = "2015"] or Cube.AttributeMemberId([Incident_ResolvedDate.YearNumber]) = "[Incident_ResolvedDate].[YearNumber].&[2016]" meta [DisplayName = "2016"] or Cube.AttributeMemberId([Incident_ResolvedDate.YearNumber]) = "[Incident_ResolvedDate].[YearNumber].&[2017]" meta [DisplayName = "2017"] or Cube.AttributeMemberId([Incident_ResolvedDate.YearNumber]) = "[Incident_ResolvedDate].[YearNumber].&[2018]" meta [DisplayName = "2018"])),
    #"Added Items1" = Cube.Transform(#"Filtered Rows1",
        {
            {Cube.AddAndExpandDimensionColumn, "[IncidentDim_IncidentClassification]", {"[IncidentDim_IncidentClassification].[IncidentClassificationValue].[IncidentClassificationValue]"}, {"IncidentDim_IncidentClassification.IncidentClassificationValue.1"}},
            {Cube.AddAndExpandDimensionColumn, "[IncidentDim_IncidentResolutionCategory]", {"[IncidentDim_IncidentResolutionCategory].[IncidentResolutionCategoryValue].[IncidentResolutionCategoryValue]"}, {"IncidentDim_IncidentResolutionCategory.IncidentResolutionCategoryValue.1"}},
            {Cube.AddAndExpandDimensionColumn, "[IncidentDim_IncidentSource]", {"[IncidentDim_IncidentSource].[IncidentSourceValue].[IncidentSourceValue]"}, {"IncidentDim_IncidentSource.IncidentSourceValue.1"}},
            {Cube.AddAndExpandDimensionColumn, "[IncidentDim_IncidentTierQueues]", {"[IncidentDim_IncidentTierQueues].[IncidentTierQueuesValue].[IncidentTierQueuesValue]"}, {"IncidentDim_IncidentTierQueues.IncidentTierQueuesValue.1"}}
        }),
    #"Removed Columns" = Table.RemoveColumns(#"Added Items1",{"IncidentDim_IncidentClassification.IncidentClassificationValue.1", "IncidentDim_IncidentResolutionCategory.IncidentResolutionCategoryValue.1", "IncidentDim_IncidentSource.IncidentSourceValue.1", "IncidentDim_IncidentTierQueues.IncidentTierQueuesValue.1"}),
    #"Added Items2" = Cube.Transform(#"Removed Columns",
        {
            {Cube.AddAndExpandDimensionColumn, "[AssignedToUserDim]", {"[AssignedToUserDim].[Department].[Department]", "[AssignedToUserDim].[DisplayName].[DisplayName]"}, {"AssignedToUserDim.Department.1", "AssignedToUserDim.Display Name (UserDim)"}},
            {Cube.AddAndExpandDimensionColumn, "[ResolvedByUserDim]", {"[ResolvedByUserDim].[Department].[Department]", "[ResolvedByUserDim].[DisplayName].[DisplayName]"}, {"ResolvedByUserDim.Department", "ResolvedByUserDim.Display Name (UserDim)"}}
        }),
    #"Removed Columns1" = Table.RemoveColumns(#"Added Items2",{"AssignedToUserDim.City", "AssignedToUserDim.Department.1"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns1",{{"Incidents Average Resolution Time (Hours)", type number}, {"Incident_CreatedDate.WeekNumberInYear", Int64.Type}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each (Cube.AttributeMemberId([Incident_CreatedDate.YearNumber]) <> "[Incident_CreatedDate].[YearNumber].&[2011]" meta [DisplayName = "2011"] and Cube.AttributeMemberId([Incident_CreatedDate.YearNumber]) <> "[Incident_CreatedDate].[YearNumber].&[2012]" meta [DisplayName = "2012"] and Cube.AttributeMemberId([Incident_CreatedDate.YearNumber]) <> "[Incident_CreatedDate].[YearNumber].&[2014]" meta [DisplayName = "2014"])),
    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"Incident_CreatedDate.CalendarDate", type datetime}, {"Incident_ResolvedDate.CalendarDate", type datetime}, {"Incidents Average Resolution Time (Hours)", type number}, {"Incidents Escalated", Int64.Type}, {"Incidents Opened", Int64.Type}}),
    #"Filtered Rows2" = Table.SelectRows(#"Changed Type1", each (Cube.AttributeMemberId([Incident_CreatedDate.YearNumber]) <> "[Incident_CreatedDate].[YearNumber].&[2013]" meta [DisplayName = "2013"])),
    #"Changed Type2" = Table.TransformColumnTypes(#"Filtered Rows2",{{"Incident_ResolvedDate.WeekNumberInYear", Int64.Type}}),
    #"Added Conditional Column" = Table.AddColumn(#"Changed Type2", "Coordinates", each if [AffectedUserDim.City] = "Leduc" and [AffectedUserDim.Company] = "Horizon Drilling" then "53.3007481,-113.5277956" else if [AffectedUserDim.City] = "Red Deer" and [AffectedUserDim.Company] = "Eagle Well Servicing" then "52.2921865,-113.8281247" else if [AffectedUserDim.City] = "Red Deer" and [AffectedUserDim.Company] = "Western Field Services" then "52.2921865,-113.8281247" else if [AffectedUserDim.City] = "Red Deer" and [AffectedUserDim.Company] = "Aero Rental Services" then "52.2879262,-113.8462393" else if [AffectedUserDim.City] = "Red Deer" and [AffectedUserDim.Company] = "Western Energy Services Corp." then "52.2921865,-113.8281247" else if [AffectedUserDim.City] = "Lloydminster" and [AffectedUserDim.Company] = "Eagle Well Servicing" then "53.2840146,-109.9739438" else if [AffectedUserDim.City] = "Clairmont" and [AffectedUserDim.Company] = "Eagle Well Servicing" then "55.2401277,-118.7789961" else if [AffectedUserDim.City] = "Estevan" and [AffectedUserDim.Company] = "Eagle Well Servicing" then "49.1330884,-102.962304" else if [AffectedUserDim.City] = "Clairmont" and [AffectedUserDim.Company] = "Aero Rental Services" then "55.2401277,-118.7789961" else if [AffectedUserDim.City] = "Fort St. John" and [AffectedUserDim.Company] = "Aero Rental Services" then "56.2215891,-120.8743784" else if [AffectedUserDim.City] = "Leduc" and [AffectedUserDim.Company] = "Western Field Services" then "53.2955142,-113.5360948" else if [AffectedUserDim.City] = "Leduc" and [AffectedUserDim.Company] = "Western Energy Services Corp." then "53.2955142,-113.5360948" else if [AffectedUserDim.City] = "Calgary" and [AffectedUserDim.Company] = "Western Field Services" then "51.0444453,-114.0675078" else if [AffectedUserDim.City] = "Calgary" and [AffectedUserDim.Company] = "Western Energy Services Corp." then "51.0444453,-114.0675078" else if [AffectedUserDim.City] = "Calgary" and [AffectedUserDim.Company] = "Eagle Well Servicing" then "51.0444004,-114.069467" else if [AffectedUserDim.City] = "Calgary" and [AffectedUserDim.Company] = "Aero Rental Services" then "51.0444453,-114.0675078" else if [AffectedUserDim.City] = "Calgary" and [AffectedUserDim.Company] = "Western Field Services" then "51.0444004,-114.069467" else if [AffectedUserDim.City] = "Calgary" and [AffectedUserDim.Company] = "Horizon Drilling" then "51.0444453,-114.0675078" else if [AffectedUserDim.City] = "Calgary" and [AffectedUserDim.Company] = "Stoneham Drilling Corporation" then "51.0444453,-114.0675078" else if [AffectedUserDim.City] = "Denver" and [AffectedUserDim.Company] = "Stoneham Drilling Corporation" then "39.7472627,-104.9914155" else if [AffectedUserDim.City] = "Williston" and [AffectedUserDim.Company] = "Stoneham Drilling Corporation" then "48.1435076,-103.7312707"
 else null)
in
    #"Added Conditional Column"
